name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  phpunit:
    strategy:
      matrix:
        php_version: [8.0, 8.1, 8.2]
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码仓库
      - uses: actions/checkout@v2

      # 2. 设置 PHP 环境
      - name: Setup PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          extensions: bcmath
          coverage: xdebug

      # 3. 安装 Composer 依赖
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 4. 运行 PHPUnit 测试
      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit --coverage-text --colors=never
